### PR TITLE
Adds schedule

### PR DESCRIPTION
**Pull request by annalorimer**

### CODE REVIEW

**Comment by arshiamufti** [comment]
lgtm 🚢 🚢

**Comment by evykassirer** [comment]
awesome! is this in the nav bar? did you confirm it looks ok for mobile?

can we also link to the schedule from the speakers + talks pages? I can also add this later, don't need it for this PR

**Comment by evykassirer** [comment]
also love the colour coding 😍

**Comment by annalorimer** [comment]
@evykassirer Yes, it looks fine on mobile. The link to the speakers page is right next to it in the navbar so I don't think we need it.

**Pull request merged**
